/* 
 * ExaVault API
 *
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ExaVault.Client.SwaggerDateConverter;

namespace ExaVault.Model
{
    /// <summary>
    /// SSHKeyRelationships
    /// </summary>
    [DataContract]
        public partial class SSHKeyRelationships :  IEquatable<SSHKeyRelationships>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SSHKeyRelationships" /> class.
        /// </summary>
        /// <param name="ownerUser">ownerUser.</param>
        public SSHKeyRelationships(SSHKeyRelationshipsOwnerUser ownerUser = default(SSHKeyRelationshipsOwnerUser))
        {
            this.OwnerUser = ownerUser;
        }
        
        /// <summary>
        /// Gets or Sets OwnerUser
        /// </summary>
        [DataMember(Name="ownerUser", EmitDefaultValue=false)]
        public SSHKeyRelationshipsOwnerUser OwnerUser { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SSHKeyRelationships {\n");
            sb.Append("  OwnerUser: ").Append(OwnerUser).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SSHKeyRelationships);
        }

        /// <summary>
        /// Returns true if SSHKeyRelationships instances are equal
        /// </summary>
        /// <param name="input">Instance of SSHKeyRelationships to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SSHKeyRelationships input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OwnerUser == input.OwnerUser ||
                    (this.OwnerUser != null &&
                    this.OwnerUser.Equals(input.OwnerUser))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OwnerUser != null)
                    hashCode = hashCode * 59 + this.OwnerUser.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
