/* 
 * ExaVault API
 *
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ExaVault.Client.SwaggerDateConverter;

namespace ExaVault.Model
{
    /// <summary>
    /// UserPermissions
    /// </summary>
    [DataContract]
        public partial class UserPermissions :  IEquatable<UserPermissions>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserPermissions" /> class.
        /// </summary>
        /// <param name="download">Download permission flag (required).</param>
        /// <param name="upload">Upload permission flag (required).</param>
        /// <param name="modify">Modify permission flag (required).</param>
        /// <param name="delete">Delete permission flag (required).</param>
        /// <param name="list">View folder contents permission flag (required).</param>
        /// <param name="changePassword">Change (own) password permission flag (required).</param>
        /// <param name="share">Sharing permission flag (required).</param>
        /// <param name="notification">Notifications permission flag (required).</param>
        /// <param name="viewFormData">Access Form Data permission flag. If true, user can view submissions that have been stored for a receive folder. This includes any data submitted in the receive folder form. (required).</param>
        /// <param name="deleteFormData">Delete form data permission flag. If true, user can remove data that was submitted for a receive folder. This applies only to data submitted in the receive folder form, not the actual files uploaded. (required).</param>
        public UserPermissions(bool? download = default(bool?), bool? upload = default(bool?), bool? modify = default(bool?), bool? delete = default(bool?), bool? list = default(bool?), bool? changePassword = default(bool?), bool? share = default(bool?), bool? notification = default(bool?), bool? viewFormData = default(bool?), bool? deleteFormData = default(bool?))
        {
            // to ensure "download" is required (not null)
            if (download == null)
            {
                throw new InvalidDataException("download is a required property for UserPermissions and cannot be null");
            }
            else
            {
                this.Download = download;
            }
            // to ensure "upload" is required (not null)
            if (upload == null)
            {
                throw new InvalidDataException("upload is a required property for UserPermissions and cannot be null");
            }
            else
            {
                this.Upload = upload;
            }
            // to ensure "modify" is required (not null)
            if (modify == null)
            {
                throw new InvalidDataException("modify is a required property for UserPermissions and cannot be null");
            }
            else
            {
                this.Modify = modify;
            }
            // to ensure "delete" is required (not null)
            if (delete == null)
            {
                throw new InvalidDataException("delete is a required property for UserPermissions and cannot be null");
            }
            else
            {
                this.Delete = delete;
            }
            // to ensure "list" is required (not null)
            if (list == null)
            {
                throw new InvalidDataException("list is a required property for UserPermissions and cannot be null");
            }
            else
            {
                this.List = list;
            }
            // to ensure "changePassword" is required (not null)
            if (changePassword == null)
            {
                throw new InvalidDataException("changePassword is a required property for UserPermissions and cannot be null");
            }
            else
            {
                this.ChangePassword = changePassword;
            }
            // to ensure "share" is required (not null)
            if (share == null)
            {
                throw new InvalidDataException("share is a required property for UserPermissions and cannot be null");
            }
            else
            {
                this.Share = share;
            }
            // to ensure "notification" is required (not null)
            if (notification == null)
            {
                throw new InvalidDataException("notification is a required property for UserPermissions and cannot be null");
            }
            else
            {
                this.Notification = notification;
            }
            // to ensure "viewFormData" is required (not null)
            if (viewFormData == null)
            {
                throw new InvalidDataException("viewFormData is a required property for UserPermissions and cannot be null");
            }
            else
            {
                this.ViewFormData = viewFormData;
            }
            // to ensure "deleteFormData" is required (not null)
            if (deleteFormData == null)
            {
                throw new InvalidDataException("deleteFormData is a required property for UserPermissions and cannot be null");
            }
            else
            {
                this.DeleteFormData = deleteFormData;
            }
        }
        
        /// <summary>
        /// Download permission flag
        /// </summary>
        /// <value>Download permission flag</value>
        [DataMember(Name="download", EmitDefaultValue=false)]
        public bool? Download { get; set; }

        /// <summary>
        /// Upload permission flag
        /// </summary>
        /// <value>Upload permission flag</value>
        [DataMember(Name="upload", EmitDefaultValue=false)]
        public bool? Upload { get; set; }

        /// <summary>
        /// Modify permission flag
        /// </summary>
        /// <value>Modify permission flag</value>
        [DataMember(Name="modify", EmitDefaultValue=false)]
        public bool? Modify { get; set; }

        /// <summary>
        /// Delete permission flag
        /// </summary>
        /// <value>Delete permission flag</value>
        [DataMember(Name="delete", EmitDefaultValue=false)]
        public bool? Delete { get; set; }

        /// <summary>
        /// View folder contents permission flag
        /// </summary>
        /// <value>View folder contents permission flag</value>
        [DataMember(Name="list", EmitDefaultValue=false)]
        public bool? List { get; set; }

        /// <summary>
        /// Change (own) password permission flag
        /// </summary>
        /// <value>Change (own) password permission flag</value>
        [DataMember(Name="changePassword", EmitDefaultValue=false)]
        public bool? ChangePassword { get; set; }

        /// <summary>
        /// Sharing permission flag
        /// </summary>
        /// <value>Sharing permission flag</value>
        [DataMember(Name="share", EmitDefaultValue=false)]
        public bool? Share { get; set; }

        /// <summary>
        /// Notifications permission flag
        /// </summary>
        /// <value>Notifications permission flag</value>
        [DataMember(Name="notification", EmitDefaultValue=false)]
        public bool? Notification { get; set; }

        /// <summary>
        /// Access Form Data permission flag. If true, user can view submissions that have been stored for a receive folder. This includes any data submitted in the receive folder form.
        /// </summary>
        /// <value>Access Form Data permission flag. If true, user can view submissions that have been stored for a receive folder. This includes any data submitted in the receive folder form.</value>
        [DataMember(Name="viewFormData", EmitDefaultValue=false)]
        public bool? ViewFormData { get; set; }

        /// <summary>
        /// Delete form data permission flag. If true, user can remove data that was submitted for a receive folder. This applies only to data submitted in the receive folder form, not the actual files uploaded.
        /// </summary>
        /// <value>Delete form data permission flag. If true, user can remove data that was submitted for a receive folder. This applies only to data submitted in the receive folder form, not the actual files uploaded.</value>
        [DataMember(Name="deleteFormData", EmitDefaultValue=false)]
        public bool? DeleteFormData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserPermissions {\n");
            sb.Append("  Download: ").Append(Download).Append("\n");
            sb.Append("  Upload: ").Append(Upload).Append("\n");
            sb.Append("  Modify: ").Append(Modify).Append("\n");
            sb.Append("  Delete: ").Append(Delete).Append("\n");
            sb.Append("  List: ").Append(List).Append("\n");
            sb.Append("  ChangePassword: ").Append(ChangePassword).Append("\n");
            sb.Append("  Share: ").Append(Share).Append("\n");
            sb.Append("  Notification: ").Append(Notification).Append("\n");
            sb.Append("  ViewFormData: ").Append(ViewFormData).Append("\n");
            sb.Append("  DeleteFormData: ").Append(DeleteFormData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UserPermissions);
        }

        /// <summary>
        /// Returns true if UserPermissions instances are equal
        /// </summary>
        /// <param name="input">Instance of UserPermissions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserPermissions input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Download == input.Download ||
                    (this.Download != null &&
                    this.Download.Equals(input.Download))
                ) && 
                (
                    this.Upload == input.Upload ||
                    (this.Upload != null &&
                    this.Upload.Equals(input.Upload))
                ) && 
                (
                    this.Modify == input.Modify ||
                    (this.Modify != null &&
                    this.Modify.Equals(input.Modify))
                ) && 
                (
                    this.Delete == input.Delete ||
                    (this.Delete != null &&
                    this.Delete.Equals(input.Delete))
                ) && 
                (
                    this.List == input.List ||
                    (this.List != null &&
                    this.List.Equals(input.List))
                ) && 
                (
                    this.ChangePassword == input.ChangePassword ||
                    (this.ChangePassword != null &&
                    this.ChangePassword.Equals(input.ChangePassword))
                ) && 
                (
                    this.Share == input.Share ||
                    (this.Share != null &&
                    this.Share.Equals(input.Share))
                ) && 
                (
                    this.Notification == input.Notification ||
                    (this.Notification != null &&
                    this.Notification.Equals(input.Notification))
                ) && 
                (
                    this.ViewFormData == input.ViewFormData ||
                    (this.ViewFormData != null &&
                    this.ViewFormData.Equals(input.ViewFormData))
                ) && 
                (
                    this.DeleteFormData == input.DeleteFormData ||
                    (this.DeleteFormData != null &&
                    this.DeleteFormData.Equals(input.DeleteFormData))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Download != null)
                    hashCode = hashCode * 59 + this.Download.GetHashCode();
                if (this.Upload != null)
                    hashCode = hashCode * 59 + this.Upload.GetHashCode();
                if (this.Modify != null)
                    hashCode = hashCode * 59 + this.Modify.GetHashCode();
                if (this.Delete != null)
                    hashCode = hashCode * 59 + this.Delete.GetHashCode();
                if (this.List != null)
                    hashCode = hashCode * 59 + this.List.GetHashCode();
                if (this.ChangePassword != null)
                    hashCode = hashCode * 59 + this.ChangePassword.GetHashCode();
                if (this.Share != null)
                    hashCode = hashCode * 59 + this.Share.GetHashCode();
                if (this.Notification != null)
                    hashCode = hashCode * 59 + this.Notification.GetHashCode();
                if (this.ViewFormData != null)
                    hashCode = hashCode * 59 + this.ViewFormData.GetHashCode();
                if (this.DeleteFormData != null)
                    hashCode = hashCode * 59 + this.DeleteFormData.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
