/* 
 * ExaVault API
 *
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AccountAllowedIpRanges
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccountAllowedIpRangesTests
    {
        // TODO uncomment below to declare an instance variable for AccountAllowedIpRanges
        //private AccountAllowedIpRanges instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccountAllowedIpRanges
            //instance = new AccountAllowedIpRanges();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountAllowedIpRanges
        /// </summary>
        [Test]
        public void AccountAllowedIpRangesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccountAllowedIpRanges
            //Assert.IsInstanceOfType<AccountAllowedIpRanges> (instance, "variable 'instance' is a AccountAllowedIpRanges");
        }


        /// <summary>
        /// Test the property 'IpStart'
        /// </summary>
        [Test]
        public void IpStartTest()
        {
            // TODO unit test for the property 'IpStart'
        }
        /// <summary>
        /// Test the property 'IpEnd'
        /// </summary>
        [Test]
        public void IpEndTest()
        {
            // TODO unit test for the property 'IpEnd'
        }

    }

}
