/* 
 * ExaVault API
 *
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Body8
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Body8Tests
    {
        // TODO uncomment below to declare an instance variable for Body8
        //private Body8 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Body8
            //instance = new Body8();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Body8
        /// </summary>
        [Test]
        public void Body8InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Body8
            //Assert.IsInstanceOfType<Body8> (instance, "variable 'instance' is a Body8");
        }


        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'FolderName'
        /// </summary>
        [Test]
        public void FolderNameTest()
        {
            // TODO unit test for the property 'FolderName'
        }
        /// <summary>
        /// Test the property 'ParentResource'
        /// </summary>
        [Test]
        public void ParentResourceTest()
        {
            // TODO unit test for the property 'ParentResource'
        }

    }

}
