/* 
 * ExaVault API
 *
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Body2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Body2Tests
    {
        // TODO uncomment below to declare an instance variable for Body2
        //private Body2 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Body2
            //instance = new Body2();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Body2
        /// </summary>
        [Test]
        public void Body2InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Body2
            //Assert.IsInstanceOfType<Body2> (instance, "variable 'instance' is a Body2");
        }


        /// <summary>
        /// Test the property 'FormDescription'
        /// </summary>
        [Test]
        public void FormDescriptionTest()
        {
            // TODO unit test for the property 'FormDescription'
        }
        /// <summary>
        /// Test the property 'SubmitButtonText'
        /// </summary>
        [Test]
        public void SubmitButtonTextTest()
        {
            // TODO unit test for the property 'SubmitButtonText'
        }
        /// <summary>
        /// Test the property 'SuccessMessage'
        /// </summary>
        [Test]
        public void SuccessMessageTest()
        {
            // TODO unit test for the property 'SuccessMessage'
        }
        /// <summary>
        /// Test the property 'Elements'
        /// </summary>
        [Test]
        public void ElementsTest()
        {
            // TODO unit test for the property 'Elements'
        }
        /// <summary>
        /// Test the property 'CssStyles'
        /// </summary>
        [Test]
        public void CssStylesTest()
        {
            // TODO unit test for the property 'CssStyles'
        }

    }

}
