/* 
 * ExaVault API
 *
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Body11
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Body11Tests
    {
        // TODO uncomment below to declare an instance variable for Body11
        //private Body11 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Body11
            //instance = new Body11();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Body11
        /// </summary>
        [Test]
        public void Body11InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Body11
            //Assert.IsInstanceOfType<Body11> (instance, "variable 'instance' is a Body11");
        }


        /// <summary>
        /// Test the property 'Resource'
        /// </summary>
        [Test]
        public void ResourceTest()
        {
            // TODO unit test for the property 'Resource'
        }
        /// <summary>
        /// Test the property 'ParentResource'
        /// </summary>
        [Test]
        public void ParentResourceTest()
        {
            // TODO unit test for the property 'ParentResource'
        }

    }

}
