/* 
 * ExaVault API
 *
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BrandingSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BrandingSettingsTests
    {
        // TODO uncomment below to declare an instance variable for BrandingSettings
        //private BrandingSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BrandingSettings
            //instance = new BrandingSettings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BrandingSettings
        /// </summary>
        [Test]
        public void BrandingSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BrandingSettings
            //Assert.IsInstanceOfType<BrandingSettings> (instance, "variable 'instance' is a BrandingSettings");
        }


        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Test]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'CustomEmail'
        /// </summary>
        [Test]
        public void CustomEmailTest()
        {
            // TODO unit test for the property 'CustomEmail'
        }
        /// <summary>
        /// Test the property 'Logo'
        /// </summary>
        [Test]
        public void LogoTest()
        {
            // TODO unit test for the property 'Logo'
        }
        /// <summary>
        /// Test the property 'LogoExt'
        /// </summary>
        [Test]
        public void LogoExtTest()
        {
            // TODO unit test for the property 'LogoExt'
        }
        /// <summary>
        /// Test the property 'Theme'
        /// </summary>
        [Test]
        public void ThemeTest()
        {
            // TODO unit test for the property 'Theme'
        }

    }

}
