/* 
 * ExaVault API
 *
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CallbackSettings1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CallbackSettings1Tests
    {
        // TODO uncomment below to declare an instance variable for CallbackSettings1
        //private CallbackSettings1 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CallbackSettings1
            //instance = new CallbackSettings1();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CallbackSettings1
        /// </summary>
        [Test]
        public void CallbackSettings1InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CallbackSettings1
            //Assert.IsInstanceOfType<CallbackSettings1> (instance, "variable 'instance' is a CallbackSettings1");
        }


        /// <summary>
        /// Test the property 'EndpointUrl'
        /// </summary>
        [Test]
        public void EndpointUrlTest()
        {
            // TODO unit test for the property 'EndpointUrl'
        }
        /// <summary>
        /// Test the property 'Triggers'
        /// </summary>
        [Test]
        public void TriggersTest()
        {
            // TODO unit test for the property 'Triggers'
        }

    }

}
