/* 
 * ExaVault API
 *
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DownloadPolling
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DownloadPollingTests
    {
        // TODO uncomment below to declare an instance variable for DownloadPolling
        //private DownloadPolling instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DownloadPolling
            //instance = new DownloadPolling();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DownloadPolling
        /// </summary>
        [Test]
        public void DownloadPollingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DownloadPolling
            //Assert.IsInstanceOfType<DownloadPolling> (instance, "variable 'instance' is a DownloadPolling");
        }


        /// <summary>
        /// Test the property 'Zip'
        /// </summary>
        [Test]
        public void ZipTest()
        {
            // TODO unit test for the property 'Zip'
        }
        /// <summary>
        /// Test the property 'Percent'
        /// </summary>
        [Test]
        public void PercentTest()
        {
            // TODO unit test for the property 'Percent'
        }

    }

}
