/* 
 * ExaVault API
 *
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NotificationAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NotificationAttributesTests
    {
        // TODO uncomment below to declare an instance variable for NotificationAttributes
        //private NotificationAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NotificationAttributes
            //instance = new NotificationAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NotificationAttributes
        /// </summary>
        [Test]
        public void NotificationAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NotificationAttributes
            //Assert.IsInstanceOfType<NotificationAttributes> (instance, "variable 'instance' is a NotificationAttributes");
        }


        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Test]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'Usernames'
        /// </summary>
        [Test]
        public void UsernamesTest()
        {
            // TODO unit test for the property 'Usernames'
        }
        /// <summary>
        /// Test the property 'Recipients'
        /// </summary>
        [Test]
        public void RecipientsTest()
        {
            // TODO unit test for the property 'Recipients'
        }
        /// <summary>
        /// Test the property 'SendEmail'
        /// </summary>
        [Test]
        public void SendEmailTest()
        {
            // TODO unit test for the property 'SendEmail'
        }
        /// <summary>
        /// Test the property 'ReadableDescription'
        /// </summary>
        [Test]
        public void ReadableDescriptionTest()
        {
            // TODO unit test for the property 'ReadableDescription'
        }
        /// <summary>
        /// Test the property 'ReadableDescriptionWithoutPath'
        /// </summary>
        [Test]
        public void ReadableDescriptionWithoutPathTest()
        {
            // TODO unit test for the property 'ReadableDescriptionWithoutPath'
        }
        /// <summary>
        /// Test the property 'ShareId'
        /// </summary>
        [Test]
        public void ShareIdTest()
        {
            // TODO unit test for the property 'ShareId'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Test]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }

    }

}
