/* 
 * ExaVault API
 *
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PreviewFileResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PreviewFileResponseTests
    {
        // TODO uncomment below to declare an instance variable for PreviewFileResponse
        //private PreviewFileResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PreviewFileResponse
            //instance = new PreviewFileResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PreviewFileResponse
        /// </summary>
        [Test]
        public void PreviewFileResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PreviewFileResponse
            //Assert.IsInstanceOfType<PreviewFileResponse> (instance, "variable 'instance' is a PreviewFileResponse");
        }


        /// <summary>
        /// Test the property 'ResponseStatus'
        /// </summary>
        [Test]
        public void ResponseStatusTest()
        {
            // TODO unit test for the property 'ResponseStatus'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
