/* 
 * ExaVault API
 *
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ResourceMultiResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResourceMultiResponseTests
    {
        // TODO uncomment below to declare an instance variable for ResourceMultiResponse
        //private ResourceMultiResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResourceMultiResponse
            //instance = new ResourceMultiResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResourceMultiResponse
        /// </summary>
        [Test]
        public void ResourceMultiResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResourceMultiResponse
            //Assert.IsInstanceOfType<ResourceMultiResponse> (instance, "variable 'instance' is a ResourceMultiResponse");
        }


        /// <summary>
        /// Test the property 'Responses'
        /// </summary>
        [Test]
        public void ResponsesTest()
        {
            // TODO unit test for the property 'Responses'
        }

    }

}
