/* 
 * ExaVault API
 *
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserPermissions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserPermissionsTests
    {
        // TODO uncomment below to declare an instance variable for UserPermissions
        //private UserPermissions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserPermissions
            //instance = new UserPermissions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserPermissions
        /// </summary>
        [Test]
        public void UserPermissionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserPermissions
            //Assert.IsInstanceOfType<UserPermissions> (instance, "variable 'instance' is a UserPermissions");
        }


        /// <summary>
        /// Test the property 'Download'
        /// </summary>
        [Test]
        public void DownloadTest()
        {
            // TODO unit test for the property 'Download'
        }
        /// <summary>
        /// Test the property 'Upload'
        /// </summary>
        [Test]
        public void UploadTest()
        {
            // TODO unit test for the property 'Upload'
        }
        /// <summary>
        /// Test the property 'Modify'
        /// </summary>
        [Test]
        public void ModifyTest()
        {
            // TODO unit test for the property 'Modify'
        }
        /// <summary>
        /// Test the property 'Delete'
        /// </summary>
        [Test]
        public void DeleteTest()
        {
            // TODO unit test for the property 'Delete'
        }
        /// <summary>
        /// Test the property 'List'
        /// </summary>
        [Test]
        public void ListTest()
        {
            // TODO unit test for the property 'List'
        }
        /// <summary>
        /// Test the property 'ChangePassword'
        /// </summary>
        [Test]
        public void ChangePasswordTest()
        {
            // TODO unit test for the property 'ChangePassword'
        }
        /// <summary>
        /// Test the property 'Share'
        /// </summary>
        [Test]
        public void ShareTest()
        {
            // TODO unit test for the property 'Share'
        }
        /// <summary>
        /// Test the property 'Notification'
        /// </summary>
        [Test]
        public void NotificationTest()
        {
            // TODO unit test for the property 'Notification'
        }
        /// <summary>
        /// Test the property 'ViewFormData'
        /// </summary>
        [Test]
        public void ViewFormDataTest()
        {
            // TODO unit test for the property 'ViewFormData'
        }
        /// <summary>
        /// Test the property 'DeleteFormData'
        /// </summary>
        [Test]
        public void DeleteFormDataTest()
        {
            // TODO unit test for the property 'DeleteFormData'
        }

    }

}
